_**Computer algebra systems and Representations of vectors and matrices in python**_


**1. Short introduction：** 

A computer algebra system \(CAS\) is any mathematical software 

that can process mathematical expressions in a manner like 

traditional manual calculations by mathematicians and scientists.



**2. Application field：**

1. Symbolic calculations and exact results

2. Equation solving and analytical calculations

3. Mathematical Derivation and Proof

4. Multi\-field application


**3. Vector representation:** 

1. Array

2. List:

3. Specialized Vector Data Types



**Vector in python**


In [11]:
#define and show horizontal vector
import numpy as np
list1 =  [1,2,3]
vector1 = np.array(list1)
print(vector1)

[1 2 3]


In [10]:
#define and show vertical vector
import numpy as np
list2 = [[10],
      [20],
      [30]]
vector2 = np.array(list2)
print(vector2)

[[10]
 [20]
 [30]]


In [12]:
#Vector addition
import numpy as np
list1 = [5, 6, 9]
list2 = [1, 2, 3]
vector1 = np.array(list1)
vector2 = np.array(list2)
addition = vector1 + vector2
print("Vector Addition: " + str(addition))

Vector Addition: [ 6  8 12]


In [14]:
#Vector subtraction
import numpy as np
list1 = [5, 6, 9]
list2 = [1, 2, 3]
vector1 = np.array(list1)
vector2 = np.array(list2)
subtraction = vector1 - vector2
print("Vector subtraction:" + str(subtraction))

Vector subtraction:[4 4 6]


In [16]:
#Vector multiplication
import numpy as np
list1 = [5, 6, 9]
list2 = [1, 2, 3]
vector1 = np.array(list1)
vector2 = np.array(list2)
multiplication = vector1 * vector2
print("Vector Multiplication:"+ str(multiplication))

Vector Multiplication:[ 5 12 27]


In [17]:
#Vector division
import numpy as np
list1 = [5, 6, 9]
list2 = [1, 2, 3]
vector1 = np.array(list1)
vector2 = np.array(list2)
division = vector1 / vector2
print("Vector division:"+ str(division))

Vector division:[5. 3. 3.]


In [19]:
# Vector Dot product
import numpy as np 
list1 = [5, 6, 9]
list2 = [1, 2, 3]
vector1 = np.array(list1)
vector2 = np.array(list2)
vctr_dot = vector1.dot(vector2)
print("Dot product of two vectors: "+str(vctr_dot))

Dot product of two vectors: 44


In [23]:
# Vector scalar multiplication
import numpy as np
list1 = [5, 6, 9]
vector1 = np.array(list1)
scalar = 2
print("Vector scalar multiplication:"+ str(scalar * vector1))

Vector scalar multiplication:[10 12 18]


**4. Matrices representation：**

1. Array

2. list nesting

3. specialized array data structure


_**Matrices in Python**_


In [28]:
#Define Matrices
import numpy as np
list1 = [5, 6, 9]
list2 = [1, 2, 3]
matrix = np.array([list1,list2])
print(matrix)

[[5 6 9]
 [1 2 3]]


In [33]:
# Accessing a specific element
import numpy as np
list1 = [5, 6, 9]
list2 = [1, 2, 3]
matrix1 = np.array([list1,list2])
element = matrix[0, 1]  # Access the element in the first row and second column
print(element)

6


In [0]:
# Accessing a row or column
import numpy as np
list1 = [5, 6, 9]
list2 = [1, 2, 3]
matrix1 = np.array([list1,list2])
row = matrix1[1, :]  # Access the entire second row
column = matrix1[:, 2]  # Access the entire third column

In [30]:
# Matrix addition
import numpy as np
list1 = [5, 6, 9]
list2 = [1, 2, 3]
list3 = [4, 5, 6]
matrix1 = np.array([list1,list2])
matrix2 = np.array([list2,list3])
print(matrix1+matrix2)

[[ 6  8 12]
 [ 5  7  9]]


In [31]:
# Matrix subtraction
import numpy as np
list1 = [5, 6, 9]
list2 = [1, 2, 3]
list3 = [4, 5, 6]
matrix1 = np.array([list1,list2])
matrix2 = np.array([list2,list3])
print(matrix1-matrix2)

[[ 4  4  6]
 [-3 -3 -3]]


In [32]:
# Matrix multiplication
import numpy as np
list1 = [5, 6, 9]
list2 = [1, 2, 3]
list3 = [4, 5, 6]
matrix1 = np.array([list1,list2])
matrix2 = np.array([list2,list3])
print(matrix1*matrix2)

[[ 5 12 27]
 [ 4 10 18]]


**Gaussian elimination**


In [2]:
import numpy as np

def swag(a, b):
    for i in range(0, len(a)):
        t = a[i]
        a[i] = b[i]
        b[i] = t

def print_matrix( info, matrix ):
    print (info)
    for i in range( 0, matrix.shape[0]):
        print('[', end='')
        for j in range( 0, matrix.shape[1]):
            if(j == matrix.shape[1] - 1): 
                print( '|', end=''),                          
            print("%5.2f" %matrix[i][j], end=' ')
            if j == matrix.shape[1] - 1:
                print(']', end=' ')
                print('\n')

def check(matrix, i, row, col):         
    if 0.00 in set(matrix[i]) and len(set(matrix[i])) == 1:     
        for j in range(row - 1, i ,-1):                        
            try:
                if not(0.00 in set(matrix[j]) and len(set(matrix[j])) == 1):    
                    swag(matrix[i], matrix[j])                                 
                    select(matrix, i, col)                                      
                    break
            except:                    
                return

def select(matrix, i, col):             
    if 0.00 in set(matrix[i]) and len(set(matrix[i])) == 1:    
        return
    for k in range(0, i):                                       
        temp = matrix[i][k] / matrix[k][k]                      
        if temp == 0:                                           
            continue
        for j in range(0, col):                                 
            matrix[i][j] = matrix[i][j] - matrix[k][j] * temp

def solve(matrix):                      
    row = matrix.shape[0]                       
    col = matrix.shape[1]                       
    for i in range(0, row):                     
        if matrix[i][i] == 0:                   
            for j in range(i + 1, row):
                if matrix[j][i] != 0:
                    swag(matrix[i], matrix[j])
                    break
        select(matrix, i, col)                  
        check(matrix, i, row, col)              

def to_one(matrix):                     
    row = matrix.shape[0]
    col = matrix.shape[1]
    for i in range(0, row):                        
        temp = matrix[i][i]
        for j in range(i, col):
            matrix[i][j] = matrix[i][j] / temp
    for i in range(0, row - 1):                    
        for j in range(i + 1, col - 1):            
            temp = matrix[i][j]                    
            for k in range(j, col):                
                matrix[i][k] = matrix[i][k] - matrix[j][k] * temp  

def judge(matrix):                      
    row = matrix.shape[0]
    col = matrix.shape[1]
    vanumlist = []
    for i in range(0, col):             
        if matrix[row - 1][i] != 0:
            vanumlist.append(matrix[row - 1][i])    
    if len(vanumlist) == 1:
        print("The equation has no solution.")
    elif len(vanumlist) == 2:
        to_one(matrix)                 
        print_matrix('Simplify the matrix into row echelon form:', matrix)
        for i in range(0, row):
            print("x%d = %4.2f" %(i,matrix[i][col - 1]), end="  ")
    else:
        print( 'The equation has more that one solution.')

matrix = np.array([ [ 1, 1, 1, 1, 1,  1],
                    [ 3, 2, 1, 1,-3, 25],
                    [ 0, 1, 2, 2, 6,-22],
                    [ 5, 4, 3, 3,-1, 27],
                    [ 2,-1, 0, 3, 2,  2]
                    ],dtype=float)
# matrix = np.array([ [1,-2,3,-1,-1,2],
#                     [1,1,-1,1,-2,1],
#                     [2,-1,1,0,-2,1],
#                     [2,2,-5,2,-1,5],
#                     ],dtype=float)
# matrix = np.array([ [2,3,11,5,2],
#                     [1,1,5,2,1],
#                     [2,1,3,2,-3],
#                     [1,1,3,4,-3],
#                     ],dtype=float)
print_matrix('The initial matrix is:', matrix)
solve(matrix)
print_matrix('The row echelon form matrix is：', matrix)
judge(matrix)

The initial matrix is:
[ 1.00  1.00  1.00  1.00  1.00 | 1.00 ] 

[ 3.00  2.00  1.00  1.00 -3.00 |25.00 ] 

[ 0.00  1.00  2.00  2.00  6.00 |-22.00 ] 

[ 5.00  4.00  3.00  3.00 -1.00 |27.00 ] 

[ 2.00 -1.00  0.00  3.00  2.00 | 2.00 ] 

The row echelon form matrix is：
[ 1.00  1.00  1.00  1.00  1.00 | 1.00 ] 

[ 0.00 -1.00 -2.00 -2.00 -6.00 |22.00 ] 

[ 0.00  0.00  4.00  7.00 18.00 |-66.00 ] 

[ 0.00  0.00  0.00  0.00  0.00 | 0.00 ] 

[ 0.00  0.00  0.00  0.00  0.00 | 0.00 ] 

The equation has more that one solution.
